XX = g++
CXXFLAGS = -std=c++11 -lboost_system -lpthread -lboost_thread
LIBRARIES = functional vector cstring map
	
main: main.o
	$(CXX) main.cpp mnozenie_macierzy.cpp macierz.cpp -o main.o $(CXXFLAGS)
