######################################################################
# Automatically generated by qmake (3.0) pon. gru 5 19:24:14 2016
######################################################################

TEMPLATE = app
TARGET = program6
INCLUDEPATH += .
QT += core gui xml
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
SOURCES += main.cpp
LIBS += -L/usr/local/lib -lqwt-qt5
