######################################################################
# Automatically generated by qmake (3.0) wt. gru 6 08:22:17 2016
######################################################################

TEMPLATE = app
TARGET = program7
INCLUDEPATH += .
QT += core gui xml
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
SOURCES += main.cpp
LIBS += -L/usr/local/lib -lqwt-qt5
